apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
## selector defines which pods the service targets (by label)
  selector:
    app: mypod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  ## type provides the information about the type of service (ClusterIP, NodePort, LoadBalancer)    
  type: ClusterIP
